vars: null
stages:
    dev:
        vars: null
        regions:
            us-west-2:
                vars:
                    iamRoleArnLambda: >-
                        arn:aws:iam::451305228097:role/strum-dev-IamRoleLambda-XUIRG5CV4V32
                    serverlessDeploymentBucketName: strum-dev-serverlessdeploymentbucket-vvff7wve9nam
